Initial Classes
RebelCode/wp-admin-menu pull request #1
Opened 2017-07-01 14:26 UTC by mecha

The initial abstract classes and traits, together with default generic implementations: `Menu` and `MenuItem`.

2017-07-01 14:27 UTC, mecha commented
Unit tests for `Menu` and `MenuItem` are currently incomplete.

2017-07-03 09:06 UTC, mecha commented
A note on the hierarchy, which can be confusing since it attempts to keep both menus and menu items using a common ancestor.

All abstract functionality can be found in `MenuElementTrait`, `MenuTrait` and `MenuItemTrait`. There are also three abstract classes, each using one of these three traits, but only the `AbstractMenuElement` class is used in this package, which `AbstractBaseMenuElement` extends.

`AbstractBaseMenu` and `AbstractBaseMenuItem` then extend that, which are used to create the concrete implementations.

![abstract-wp-admin-menu-hierarchy](https://user-images.githubusercontent.com/5425482/27785936-749bf8ba-5fdf-11e7-8e64-86448c119744.png)

2017-07-24 07:36 UTC, XedinUnknown requested changes
Documentation needs to be added about what kind of exceptions methods throw.
Also, the recursive iteration seems to be a problem to discuss in-depth.

2017-07-24 07:36 UTC, XedinUnknown commented on src/AbstractMenuElement.php
> +     */
Looks like `@throws` is missing

2017-07-24 07:36 UTC, XedinUnknown commented on src/AbstractMenuElement.php
> +     */
Looks like `@throws` is missing

2017-07-24 07:36 UTC, XedinUnknown commented on src/AbstractMenuElement.php
> +     */
Looks like `@throws` is missing.

2017-07-24 07:36 UTC, XedinUnknown commented on src/AbstractMenuElement.php
> +     * @param string[]|StringableInterface[]|\Traversable $validationErrors The validation errors.
Could we make this a bit shorter?

2017-07-24 07:36 UTC, XedinUnknown commented on src/AbstractMenuElement.php
> +            throw $this->_createValidationFailedException('Parent is not a valid menu element.', 0, null, $parent);
Looks like no reasons for failed validation are given.

2017-07-24 07:36 UTC, XedinUnknown commented on src/AbstractMenuElement.php
> +            throw $this->_createValidationFailedException('Child is not a valid menu element.', 0, null, $child);
Looks like no reasons for failed validation are given.

2017-07-24 07:36 UTC, XedinUnknown commented on src/AbstractMenuElement.php
> +     *
A description of what happens would be great.

2017-07-24 07:36 UTC, XedinUnknown commented on src/AbstractBaseMenuElement.php
> +        return new RecursiveArrayIterator($this->_getChildren());
Make factory method for this.

2017-07-24 07:36 UTC, XedinUnknown commented on src/AbstractBaseMenuElement.php
> +        // What to do here? ChildrenAware::hasChildren() or RecursiveIterator::hasChildren() ?
Yes, we have a problem. I also faced this problem with my `ConfigInterface` implementation. I have an idea of how to solve this using proper SoC. Let's talk about that ASAP.

2017-07-24 07:48 UTC, mecha commented on src/AbstractMenuElement.php
> +     */
It's inherited from `ChildrenAwareTrait#_validateChild()`.

2017-07-24 08:00 UTC, mecha commented on src/AbstractMenuElement.php
> +            throw $this->_createValidationFailedException('Parent is not a valid menu element.', 0, null, $parent);
Actually, menus are not meant to be parent-aware. I had forgotten to remove the trait.

2017-07-24 08:50 UTC, mecha commented on src/AbstractMenuElement.php
> +     * @param string[]|StringableInterface[]|\Traversable $validationErrors The validation errors.
Don't know. Can we?

2017-07-24 09:10 UTC, mecha commented on src/AbstractMenuElement.php
> +     */
Method has been removed. Reason: menu elements should not be parent-aware.

2017-08-01 09:50 UTC, XedinUnknown commented on src/AbstractMenuElement.php
> +     * @param string[]|StringableInterface[]|\Traversable $validationErrors The validation errors.
E.g. by aliasing `StringableInterface` to `Stringable`, like I always do, and by `use`ing `Traversable`.

2017-08-07 10:10 UTC, XedinUnknown commented
OMG the `class RecursiveMenuIterator extends AbstractBaseRecursiveIterator` is so amaze!!! @mecha, I cri of joi.

2018-05-09 15:58 UTC, merged